using System.Collections.Generic;
using System.Linq;
using System;

namespace Org.GraphStream.Stream.File.Pajek
{
/*
 * This file is part of GraphStream <http://graphstream-project.org>.
 * 
 * GraphStream is a library whose purpose is to handle static or dynamic
 * graph, create them from scratch, file or any source and display them.
 * 
 * This program is free software distributed under the terms of two licenses, the
 * CeCILL-C license that fits European law, and the GNU Lesser General Public
 * License. You can  use, modify and/ or redistribute the software under the terms
 * of the CeCILL-C license as circulated by CEA, CNRS and INRIA at the following
 * URL <http://www.cecill.info> or under the terms of the GNU LGPL as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C and LGPL licenses and that you accept their terms.
 */


/// <summary>
/// Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start()
/// </summary>
public interface PajekParserConstants {

	/// <summary>
/// End of File.
/// </summary>
	int EOF = 0;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int EOL = 3;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DIGIT = 4;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int HEXDIGIT = 5;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int INT = 6;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int REAL = 7;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int STRING = 8;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int NETWORK = 9;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int VERTICES = 10;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ARCS = 11;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int EDGES = 12;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int EDGESLIST = 13;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ARCSLIST = 14;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int MATRIX = 15;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int COMMENT = 16;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ELLIPSE = 17;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DIAMOND = 18;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int CROSS = 19;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int BOX = 20;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TRIANGLE = 21;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int EMPTY = 22;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SIZE = 23;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int XFACT = 24;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int YFACT = 25;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int PHI = 26;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int R = 27;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int Q = 28;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int IC = 29;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int BC = 30;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int BW = 31;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LC = 32;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LA = 33;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LR = 34;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LPHI = 35;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int FOS = 36;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int FONT = 37;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int C = 38;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int P = 39;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int W = 40;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int S = 41;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int A = 42;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int AP = 43;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int L = 44;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LP = 45;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int H1 = 46;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int H2 = 47;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int K1 = 48;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int K2 = 49;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int A1 = 50;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int A2 = 51;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int B = 52;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int KEY = 53;

	/// <summary>
/// Lexical state.
/// </summary>
	int DEFAULT = 0;

	/// <summary>
/// Literal token values.
/// </summary>
	string[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "<EOL>", "<DIGIT>", "<HEXDIGIT>", "<INT>", "<REAL>",
			"<STRING>", "\"*network\"", "\"*vertices\"", "\"*arcs\"", "\"*edges\"", "\"*edgeslist\"", "\"*arcslist\"",
			"\"*matrix\"", "<COMMENT>", "\"ellipse\"", "\"diamond\"", "\"cross\"", "\"box\"", "\"triangle\"",
			"\"empty\"", "<SIZE>", "\"x_fact\"", "\"y_fact\"", "\"phi\"", "\"r\"", "\"q\"", "\"ic\"", "\"bc\"",
			"\"bw\"", "\"lc\"", "\"la\"", "\"lr\"", "\"lphi\"", "\"fos\"", "\"font\"", "\"c\"", "\"p\"", "\"w\"",
			"\"s\"", "\"a\"", "\"ap\"", "\"l\"", "\"lp\"", "\"h1\"", "\"h2\"", "\"k1\"", "\"k2\"", "\"a1\"", "\"a2\"",
			"\"b\"", "<KEY>", };

}

}
