using System.Collections.Generic;
using System.Linq;
using System;

namespace Org.GraphStream.UI.GraphicGraph.StyleSheet.Parser
{
/*
 * This file is part of GraphStream <http://graphstream-project.org>.
 * 
 * GraphStream is a library whose purpose is to handle static or dynamic
 * graph, create them from scratch, file or any source and display them.
 * 
 * This program is free software distributed under the terms of two licenses, the
 * CeCILL-C license that fits European law, and the GNU Lesser General Public
 * License. You can  use, modify and/ or redistribute the software under the terms
 * of the CeCILL-C license as circulated by CEA, CNRS and INRIA at the following
 * URL <http://www.cecill.info> or under the terms of the GNU LGPL as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C and LGPL licenses and that you accept their terms.
 */


/// <summary>
/// Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start()
/// </summary>
public interface StyleSheetParserConstants {

	/// <summary>
/// End of File.
/// </summary>
	int EOF = 0;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int EOL = 5;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DIGIT = 6;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int HEXDIGIT = 7;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int UNITS = 8;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DOT = 9;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LBRACE = 10;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int RBRACE = 11;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LPAREN = 12;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int RPAREN = 13;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SHARP = 14;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int COLON = 15;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SEMICOLON = 16;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int COMA = 17;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int RGBA = 18;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int RGB = 19;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int HTMLCOLOR = 20;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int REAL = 21;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int STRING = 22;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int System.Uri = 23;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int GRAPH = 24;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int EDGE = 25;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int NODE = 26;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SPRITE = 27;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int FILLMODE = 28;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int FILLCOLOR = 29;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int FILLIMAGE = 30;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int STROKEMODE = 31;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int STROKECOLOR = 32;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int STROKEWIDTH = 33;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SHADOWMODE = 34;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SHADOWCOLOR = 35;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SHADOWWIDTH = 36;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SHADOWOFFSET = 37;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTMODE = 38;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTCOLOR = 39;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTSTYLE = 40;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTFONT = 41;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTSIZE = 42;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTVISIBILITYMODE = 43;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTVISIBILITY = 44;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTBACKGROUNDMODE = 45;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTBACKGROUNDCOLOR = 46;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTOFFSET = 47;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTPADDING = 48;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ICONMODE = 49;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ICON = 50;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int PADDING = 51;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ZINDEX = 52;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int VISIBILITYMODE = 53;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int VISIBILITY = 54;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SHAPE = 55;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SIZE = 56;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SIZEMODE = 57;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SHAPEPOINTS = 58;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTALIGNMENT = 59;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int JCOMPONENT = 60;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ARROWIMGURL = 61;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ARROWSIZE = 62;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ARROWSHAPE = 63;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SPRITEORIENT = 64;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int CANVASCOLOR = 65;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int PLAIN = 66;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DYNPLAIN = 67;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DYNSIZE = 68;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DYNICON = 69;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DASHES = 70;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DOTS = 71;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DOUBLE = 72;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int GRADIENTDIAGONAL1 = 73;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int GRADIENTDIAGONAL2 = 74;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int GRADIENTHORIZONTAL = 75;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int GRADIENTRADIAL = 76;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int GRADIENTVERTICAL = 77;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int HIDDEN = 78;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int IMAGETILED = 79;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int IMAGESCALED = 80;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int IMAGESCALEDRATIOMAX = 81;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int IMAGESCALEDRATIOMIN = 82;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int NONE = 83;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int NORMAL = 84;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TRUNCATED = 85;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ZOOMRANGE = 86;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ATZOOM = 87;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int UNDERZOOM = 88;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int OVERZOOM = 89;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ZOOMS = 90;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int FIT = 91;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int BOLD = 92;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int BOLD_ITALIC = 93;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ITALIC = 94;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ALONG = 95;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ATLEFT = 96;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ATRIGHT = 97;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int CENTER = 98;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LEFT = 99;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int RIGHT = 100;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int UNDER = 101;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ABOVE = 102;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int JUSTIFY = 103;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int CIRCLE = 104;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TRIANGLE = 105;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int FREEPLANE = 106;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTBOX = 107;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTROUNDEDBOX = 108;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTCIRCLE = 109;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTDIAMOND = 110;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTPARAGRAPH = 111;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int BOX = 112;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ROUNDEDBOX = 113;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int CROSS = 114;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DIAMOND = 115;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int POLYGON = 116;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int BUTTON = 117;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TEXTFIELD = 118;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int PANEL = 119;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LINE = 120;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int POLYLINE = 121;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int POLYLINESCALED = 122;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ANGLE = 123;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int CUBICCURVE = 124;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int BLOB = 125;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SQUARELINE = 126;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LSQUARELINE = 127;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int HSQUARELINE = 128;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int VSQUARELINE = 129;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int ARROW = 130;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int FLOW = 131;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int PIECHART = 132;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int IMAGE = 133;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int IMAGES = 134;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int FROM = 135;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int NODE0 = 136;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int TO = 137;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int NODE1 = 138;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int PROJECTION = 139;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int CLICKED = 140;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SELECTED = 141;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int IDENTIFIER = 142;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int COMMENT = 143;

	/// <summary>
/// Lexical state.
/// </summary>
	int DEFAULT = 0;

	/// <summary>
/// Literal token values.
/// </summary>
	string[] tokenImage = { "<EOF>", "\" \"", "\"\\r\"", "\"\\t\"", "\"\\n\"", "<EOL>", "<DIGIT>", "<HEXDIGIT>",
			"<UNITS>", "\".\"", "\"{\"", "\"}\"", "\"(\"", "\")\"", "\"#\"", "\":\"", "\";\"", "\",\"", "\"rgba\"",
			"\"rgb\"", "<HTMLCOLOR>", "<REAL>", "<STRING>", "\"url\"", "\"graph\"", "\"edge\"", "\"node\"",
			"\"sprite\"", "\"fill-mode\"", "\"fill-color\"", "\"fill-image\"", "\"stroke-mode\"", "\"stroke-color\"",
			"\"stroke-width\"", "\"shadow-mode\"", "\"shadow-color\"", "\"shadow-width\"", "\"shadow-offset\"",
			"\"text-mode\"", "\"text-color\"", "\"text-style\"", "\"text-font\"", "\"text-size\"",
			"\"text-visibility-mode\"", "\"text-visibility\"", "\"text-background-mode\"", "\"text-background-color\"",
			"\"text-offset\"", "\"text-padding\"", "\"icon-mode\"", "\"icon\"", "\"padding\"", "\"z-index\"",
			"\"visibility-mode\"", "\"visibility\"", "\"shape\"", "\"size\"", "\"size-mode\"", "\"shape-points\"",
			"\"text-alignment\"", "\"jcomponent\"", "\"arrow-image\"", "\"arrow-size\"", "\"arrow-shape\"",
			"\"sprite-orientation\"", "\"canvas-color\"", "\"plain\"", "\"dyn-plain\"", "\"dyn-size\"", "\"dyn-icon\"",
			"\"dashes\"", "\"dots\"", "\"double\"", "\"gradient-diagonal1\"", "\"gradient-diagonal2\"",
			"\"gradient-horizontal\"", "\"gradient-radial\"", "\"gradient-vertical\"", "\"hidden\"", "\"image-tiled\"",
			"\"image-scaled\"", "\"image-scaled-ratio-max\"", "\"image-scaled-ratio-min\"", "\"none\"", "\"normal\"",
			"\"truncated\"", "\"zoom-range\"", "\"at-zoom\"", "\"under-zoom\"", "\"over-zoom\"", "\"zooms\"", "\"fit\"",
			"\"bold\"", "\"bold-italic\"", "\"italic\"", "\"along\"", "\"at-left\"", "\"at-right\"", "\"center\"",
			"\"left\"", "\"right\"", "\"under\"", "\"above\"", "\"justify\"", "\"circle\"", "\"triangle\"",
			"\"freeplane\"", "\"text-box\"", "\"text-rounded-box\"", "\"text-circle\"", "\"text-diamond\"",
			"\"text-paragraph\"", "\"box\"", "\"rounded-box\"", "\"cross\"", "\"diamond\"", "\"polygon\"", "\"button\"",
			"\"text-field\"", "\"panel\"", "\"line\"", "\"polyline\"", "\"polyline-scaled\"", "\"angle\"",
			"\"cubic-curve\"", "\"blob\"", "\"square-line\"", "\"L-square-line\"", "\"horizontal-square-line\"",
			"\"vertical-square-line\"", "\"arrow\"", "\"flow\"", "\"pie-chart\"", "\"image\"", "\"images\"", "\"from\"",
			"\"node0\"", "\"to\"", "\"node1\"", "\"projection\"", "\"clicked\"", "\"selected\"", "<IDENTIFIER>",
			"<COMMENT>", };

}

}
