using System.Collections.Generic;
using System.Linq;
using System;

namespace Org.GraphStream.Stream.File.Dot
{
/*
 * This file is part of GraphStream <http://graphstream-project.org>.
 * 
 * GraphStream is a library whose purpose is to handle static or dynamic
 * graph, create them from scratch, file or any source and display them.
 * 
 * This program is free software distributed under the terms of two licenses, the
 * CeCILL-C license that fits European law, and the GNU Lesser General Public
 * License. You can  use, modify and/ or redistribute the software under the terms
 * of the CeCILL-C license as circulated by CEA, CNRS and INRIA at the following
 * URL <http://www.cecill.info> or under the terms of the GNU LGPL as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C and LGPL licenses and that you accept their terms.
 */


/// <summary>
/// Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start()
/// </summary>
public interface DOTParserConstants {

	/// <summary>
/// End of File.
/// </summary>
	int EOF = 0;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int EOL = 7;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DIGIT = 8;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int HEXDIGIT = 9;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LSQBR = 10;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int RSQBR = 11;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int LBRACE = 12;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int RBRACE = 13;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int COLON = 14;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int COMMA = 15;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int EQUALS = 16;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int GRAPH = 17;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int DIGRAPH = 18;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int SUBGRAPH = 19;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int NODE = 20;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int EDGE = 21;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int STRICT = 22;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int EDGE_OP = 23;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int REAL = 24;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int STRING = 25;
	/// <summary>
/// RegularExpression Id.
/// </summary>
	int WORD = 26;

	/// <summary>
/// Lexical state.
/// </summary>
	int DEFAULT = 0;

	/// <summary>
/// Literal token values.
/// </summary>
	string[] tokenImage = { "<EOF>", "\" \"", "\"\\r\"", "\"\\t\"", "\"\\n\"", "<token of kind 5>", "<token of kind 6>",
			"<EOL>", "<DIGIT>", "<HEXDIGIT>", "\"[\"", "\"]\"", "\"{\"", "\"}\"", "\":\"", "\",\"", "\"=\"",
			"\"graph\"", "\"digraph\"", "\"subgraph\"", "\"node\"", "\"edge\"", "\"strict\"", "<EDGE_OP>", "<REAL>",
			"<STRING>", "<WORD>", "\";\"", "\"n\"", "\"ne\"", "\"e\"", "\"se\"", "\"s\"", "\"sw\"", "\"w\"", "\"nw\"",
			"\"c\"", "\"_\"", };

}

}
